#pragma once

#include <stdint.h>
#include <stdbool.h>

/*
 * alert_manager.h — TinyGuard Monitor
 *
 * Creates, stores, and retrieves alerts generated by the detection engine.
 *
 * Alert levels (from MVP spec):
 *   INFO     — device connected, learning complete
 *   WARNING  — RSSI anomaly, reconnect anomaly, stream anomaly
 *   CRITICAL — missing heartbeat, device offline
 *
 * Storage:
 *   Circular buffer of ALERT_HISTORY_SIZE alerts. When full, oldest is
 *   overwritten. No heap allocation.
 *
 * Thread safety:
 *   All operations protected by internal mutex. Safe to call from any task.
 */

#define ALERT_HISTORY_SIZE  32
#define ALERT_MSG_LEN       96

typedef enum {
    ALERT_LEVEL_INFO     = 0,
    ALERT_LEVEL_WARNING  = 1,
    ALERT_LEVEL_CRITICAL = 2,
} alert_level_t;

typedef enum {
    ALERT_TYPE_CORRELATION_ANOMALY,
    ALERT_TYPE_DEVICE_CONNECTED,
    ALERT_TYPE_LEARNING_COMPLETE,
    ALERT_TYPE_HEARTBEAT_MISSING,
    ALERT_TYPE_DEVICE_OFFLINE,
    ALERT_TYPE_RSSI_ANOMALY,
    ALERT_TYPE_RECONNECT_ANOMALY,
    ALERT_TYPE_STREAM_ANOMALY,
} alert_type_t;

typedef struct {
    uint32_t      timestamp_ms;  /* esp_log_timestamp() when alert fired  */
    alert_level_t level;
    alert_type_t  type;
    char          message[ALERT_MSG_LEN];
    float         observed;      /* the value that triggered the alert    */
    float         mean;          /* baseline mean at time of alert        */
    float         stddev;        /* baseline stddev at time of alert      */
    float         zscore;        /* z-score (0 for non-metric alerts)     */
} alert_t;

void    alert_manager_init(void);

/*
 * Create and store an alert. Logs to serial immediately.
 * zscore/observed/mean/stddev are 0 for non-metric alerts (INFO, CRITICAL).
 */
void    alert_manager_raise(alert_level_t level, alert_type_t type,
                             const char *message,
                             float observed, float mean,
                             float stddev, float zscore);

/* Convenience wrappers */
void    alert_raise_info(alert_type_t type, const char *message);
void    alert_raise_critical(alert_type_t type, const char *message);

/* Returns total alerts raised since boot */
uint32_t alert_manager_count(void);

/*
 * Copy up to `max_count` most recent alerts into `out`.
 * Returns the number actually copied.
 */
int     alert_manager_get_recent(alert_t *out, int max_count);
