#pragma once

#include <stdint.h>
#include <stdbool.h>

/*
 * alert_manager.h — TinyGuard Monitor
 *
 * Creates, stores, and retrieves alerts generated by the detection engine.
 *
 * Alert levels:
 *   INFO     — device connected, learning complete
 *   WARNING  — metric anomalies, correlation anomalies, PDS elevated
 *   CRITICAL — missing heartbeat, device offline, PDS critical
 *
 * Storage:
 *   Circular buffer of ALERT_HISTORY_SIZE alerts. When full, oldest is
 *   overwritten. No heap allocation.
 *
 * Thread safety:
 *   All operations protected by internal mutex. Safe to call from any task.
 */

#define ALERT_HISTORY_SIZE  32
#define ALERT_MSG_LEN       96

typedef enum {
    ALERT_LEVEL_INFO     = 0,
    ALERT_LEVEL_WARNING  = 1,
    ALERT_LEVEL_CRITICAL = 2,
} alert_level_t;

typedef enum {
    /* Phase 1 */
    ALERT_TYPE_DEVICE_CONNECTED,
    ALERT_TYPE_LEARNING_COMPLETE,
    ALERT_TYPE_HEARTBEAT_MISSING,
    ALERT_TYPE_DEVICE_OFFLINE,
    ALERT_TYPE_RSSI_ANOMALY,
    ALERT_TYPE_HB_INTERVAL_ANOMALY,     /* HB timing z-score — distinct from timeout */
    ALERT_TYPE_RECONNECT_ANOMALY,
    ALERT_TYPE_STREAM_ANOMALY,
    /* Phase 2 */
    ALERT_TYPE_CORRELATION_ANOMALY,
    ALERT_TYPE_PDS_ELEVATED,            /* PDS >= PDS_THRESH_ELEVATED, WARNING  */
    ALERT_TYPE_PDS_CRITICAL,            /* PDS >= PDS_THRESH_CRITICAL, CRITICAL */
} alert_type_t;

typedef struct {
    uint32_t      timestamp_ms;
    alert_level_t level;
    alert_type_t  type;
    char          message[ALERT_MSG_LEN];
    float         observed;
    float         mean;
    float         stddev;
    float         zscore;
} alert_t;

void     alert_manager_init(void);

void     alert_manager_raise(alert_level_t level, alert_type_t type,
                              const char *message,
                              float observed, float mean,
                              float stddev, float zscore);

void     alert_raise_info(alert_type_t type, const char *message);
void     alert_raise_critical(alert_type_t type, const char *message);

uint32_t alert_manager_count(void);

int      alert_manager_get_recent(alert_t *out, int max_count);
